#define CONFIG_PROGNAME                 "berk"
#define CONFIG_VERSION                  "0.0.1"
#define CONFIG_ROOT                     ".berk"
#define CONFIG_MAIN                     CONFIG_ROOT "/config"
#define CONFIG_LOGS                     CONFIG_ROOT "/logs"
#define CONFIG_REMOTES                  CONFIG_ROOT "/remotes"
#define CONFIG_HOOKS                    CONFIG_ROOT "/hooks"
