int error(char *format, ...);
int error_init(void);
int error_remote_init(char *name);
int error_remote_load(char *name);
int error_remote_save(char *name);
int error_remote_run_update(char *name, unsigned int index, char *type);
int error_missing(void);
int error_toomany(void);
int error_flag_unrecognized(char *arg);
int error_arg_invalid(char *arg);
int error_arg_parse(char *arg, char *type);
