int util_error(char *format, ...);
int util_checkalnum(char *str);
int util_checkalpha(char *str);
int util_checkdigit(char *str);
int util_checkprint(char *str);
int util_checkspace(char *str);
void util_trim(char *str);
void util_strip(char *str);
unsigned int util_split(char *str);
char *util_nextword(char *str, unsigned int index, unsigned int total);
