int util_error(char *format, ...);
char *util_assert_alnum(char *str);
char *util_assert_alpha(char *str);
char *util_assert_digit(char *str);
char *util_assert_xdigit(char *str);
char *util_assert_print(char *str);
char *util_assert_space(char *str);
char *util_assert_printspace(char *str);
void util_trim(char *str);
void util_strip(char *str);
unsigned int util_split(char *str);
char *util_nextword(char *str, unsigned int index, unsigned int total);
int util_mkdir(char *path);
int util_unlink(char *path);
unsigned int util_hash(char *str);
